version: '3'

services:
  app:
    build: .
    container_name: api_github
    tty: true
    restart: always
    volumes:
      - .:/usr/src/app
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
